# Generated by Django 3.0.7 on 2020-08-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='authorname',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='topicname',
        ),
    ]
