# Generated by Django 3.0.7 on 2020-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_auto_20200801_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
