# Generated by Django 3.0.7 on 2020-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_quotemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
